services:
  jobmanager:
    container_name: jobmanager
    hostname: jobmanager
    build:
      context: ./flink-monitor   # relative path to the Nifi Dockerfile
    ports:
      - "8082:8082"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ${JOBMANAGER_RPC_ADDRESS}
        parallelism.default: ${FLINK_PARALLELISM_DEFAULT}
        rest.address: ${JOBMANAGER_REST_ADDR}
        rest.port: ${JOBMANAGER_REST_PORT}
#    networks: # networks to connect
#      flink_network: # the name of the network
#        ipv4_address: 10.0.0.10 # static ip of the container

  taskmanager:
    build:
      context: ./flink-monitor   # relative path to the Nifi Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ${TASKMANAGER_RPC_ADDRESS}
        taskmanager.numberOfTaskSlots: ${TASKMANAGER_NUMBER_OF_TASK_SLOTS}
        parallelism.default: ${FLINK_PARALLELISM_DEFAULT}
#    networks: # networks to connect
#      flink_network: # the name of the network

#networks:
#  flink_network:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.0.0.0/24
#          gateway: 10.0.0.254