services:
  jobmanager:
    container_name: jobmanager
    hostname: jobmanager
    build:
      context: .   # relative path to the Nifi Dockerfile
      dockerfile: flink.Dockerfile
    ports:
      - "8082:8082"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ${JOBMANAGER_RPC_ADDRESS}
        parallelism.default: ${FLINK_PARALLELISM_DEFAULT}
        rest.address: ${JOBMANAGER_REST_ADDR}
        rest.port: ${JOBMANAGER_REST_PORT}
#    networks: # networks to connect
#      flink_network: # the name of the network
#        ipv4_address: 10.0.0.10 # static ip of the container

  taskmanager:
    build:
      context: .   # relative path to the Nifi Dockerfile
      dockerfile: flink.Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ${TASKMANAGER_RPC_ADDRESS}
        taskmanager.numberOfTaskSlots: ${TASKMANAGER_NUMBER_OF_TASK_SLOTS}
        parallelism.default: ${FLINK_PARALLELISM_DEFAULT}
#    networks: # networks to connect
#      flink_network: # the name of the network

#  zookeeper:
#    image: wurstmeister/zookeeper:latest
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka:latest
#    ports:
#      - "9092:9092"
#    expose:
#      - "9093"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
#      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "input-topic:1:1,output-topic:1:1"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

#networks:
#  flink_network:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.0.0.0/24
#          gateway: 10.0.0.254